### ISSUE TITLE
AA - trial does not start because IR sensor is not triggered

### ISSUE THREAD

**Issue by joseferncruz** [joseferncruz/arduino#4]
**Problem:** If the subject does not trigger the infrared sensor, the trial will continue forever. 

A possible solution is to define a time timer for sensor detection during trials. If the sensor fails to be triggered, initiate next CS-US cycle.

**Comment by audreyyin9877** [comment]
Solution is to set a 30 second timer for how long Arduino will search for the initial position of the subject. If after 30 seconds, both left and right compartments are unactive, then it will force start the next trial. This should belong in the else conditional... 

Proposed serial output to let the user know the trial was untriggered: 
- MOTION DETECTION FAILED
- NO MOTION DETECTED IN _____ SEC 
- US > ON
- US > OFF

Relates to #16
